#!/bin/bash

opkg update
echo UPDATE SUKSES .................................................
opkg install bash
echo ...............................................................
echo ...............................................................
echo ...............................................................
echo Installer SUKSES...............................................
curl -LO https://raw.githubusercontent.com/boychongzen18/MIHOMO/refs/heads/main/mihomo.tar
tar -xvf mihomo.tar
